myProject/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
    path("authenticated_view/", views.authenticated_view, name="authenticated_view"),
]

myProject/members/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "members"

urlpatterns = [
    # Django Authentication URLS
    path("sign_in/", views.sign_in, name="sign_in"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("sign_out/", views.sign_out, name="sign_out"),
    path("password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

myProject/myProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
    path('members/', include('members.urls')),
]

myProject/main/models.py
from django.db import models

# Create your models here.

myProject/members/models.py
from django.db import models

# Create your models here.

myProject/main/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


def index(request):
    template = "main/index.html"
    return render(request, template)


@login_required(login_url="/members/sign_in/?status=2")
def authenticated_view(request):
    template = "main/authenticated_view.html"
    return render(request, template)

myProject/members/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout


def sign_in(request):
    """
    A simple login with Django Auth
    status = 0 : Success Sign In
    status = 1 : Not Authenticate
    status = 2 : Need to sign in
    """
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        """ Authenticate user """
        user = authenticate(request, username=username, password=password)
        """ If user us true login """
        if user is not None:
            login(request, user)
            return redirect("/members/sign_in/?status=0")
        else:
            return redirect("/members/sign_in/?status=1")

    """ Raise status if have some error in sign in POST """
    if request.method == "GET":
        status = request.GET.get("status")
        template = "registration/sign_in.html"
        context = {
            "status": status,
        }
        return render(request, template, context)


def sign_up(request):
    """
    A simple registration with Django Auth
    status = 0 : Success Sign Up
    status = 1 : Username or Email already exist
    status = 2 : Username empty
    status = 3 : Email empty
    status = 4 : Password empty
    """
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        email = request.POST["email"]

        """ Check for empty username and password """
        if not username.strip():
            return redirect("/members/sign_up/?status=2")
        if not email.strip():
            return redirect("/members/sign_up/?status=3")
        if not password:
            return redirect("/members/sign_up/?status=4")

        """ Check if user and email already exist """
        user = User.objects.filter(username=username)
        mail = User.objects.filter(email=email)
        if user or mail:
            return redirect("/members/sign_up/?status=1")

        """ Create user """
        if username and password:
            new_user = User.objects.create_user(
                username=username, password=password, email=email
            )
            new_user.save()
            return redirect("/members/sign_up/?status=0")

    """ Raise status if have some error in sign up POST """
    if request.method == "GET":
        status = request.GET.get("status")
        template = "registration/sign_up.html"
        context = {
            "status": status,
        }
        return render(request, template, context)


def sign_out(request):
    """
    A simple logout with Django Auth
    """
    template = "main/index.html"
    context = {}

    if request.user.is_authenticated:
        logout(request)
        return render(request, template, context)
    else:
        return redirect("main:index")

myProject/templates/main/authenticated_view.html
{% extends "main/base.html" %}
{% load static %}
{% block title %} Authenticated View {% endblock %}
{% block content %}

<!-- Album- Designer Works -->
<h1 class="display-5 fw-bold lh-1">Success</h1>
<p class="lead">You can see this page, because you are authenticated</p>

{% endblock %}

myProject/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>{% block title %} {% endblock %}</title>
    <meta charset="UTF-8">
    <!-- Static CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>
    <!-- Bootstrap - CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- Bootstrap - JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
            crossorigin="anonymous">
    </script>
    <!-- Viewport Responsive -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
<div>

</div>
<!-- Collapsed Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
    <div class="container">
        <!-- Menu - Brand -->
        <a class="navbar-brand" href="{% url 'main:index' %}">bmcr</a>

        <!-- Menu Collapse - Button -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain"
                aria-controls="navbarMain" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Menu Collapse - Content -->
        <div class="collapse navbar-collapse justify-content-center" id="navbarMain">
            <ul class="navbar-nav mb-2">
                <!-- Menu - Authenticated View -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:authenticated_view' %}" role="button">
                        Authenticated View
                    </a>
                </li>
            </ul>
        </div>

        <!-- Menu - Auth -->
        <div class="navbar-nav justify-content-end mb-2">
            {% if user.is_authenticated %}
            <li class="navbar-text">
                {{ user.username }}
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'members:sign_out' %}">Sign Out</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'members:sign_in' %}">Sign In</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'members:sign_up' %}">Sign Up</a>
            </li>
            {% endif %}
        </div>

    </div>
</nav>

<!-- Block Content -->
<div class="container min-vh-100 d-flex justify-content-center align-items-center">
    <div class="row">
        <div>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        </div>
    </div>
</div>

<!-- Footer -->
<footer class="d-flex flex-wrap p-3 justify-content-center shadow text-center">
    <small class="col-4 text-muted">© 2022 bmcr, All Rights Reserved</small>
</footer>

</body>
</html>

myProject/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}
{% block title %} BMCR - Home {% endblock %}
{% block content %}

<h1 class="display-5 fw-bold lh-1">Basic Django Authentication</h1>
<p class="lead">A basic example of using authentication with Django</p>

{% endblock %}